### ISSUE TITLE
Mumudvb does not handle ECM pids that are described in PMT ES sections

### ISSUE THREAD

**Issue by malakudi** [braice/MuMuDVB#232]
mumudvb is unable to find ecm pids that are described in PMT ES sections. It only finds ecm pids that are described in the main PMT loop.
Similar issue for dvblast was fixed in this commit: https://code.videolan.org/videolan/dvblast/commit/38ef6490a2f0e60d2a7fe9c1d4f3c8f22e8af2b2

Example pmt table that doesn't work (VH1 on Astra1, 19.2E, 11973 V):
```
new PMT program=28656 version=21 pcrpid=8156
  * ES pid=3061 streamtype=0x02 streamtype_txt="13818-2 video (MPEG-2)"
    - desc 09 ca sysid=0x500 pid=8106
    - desc 09 ca sysid=0xb00 pid=1990
    - desc 09 ca sysid=0xd96 pid=6202
    - desc 09 ca sysid=0x100 pid=6126
    - desc 09 ca sysid=0x1810 pid=6122
    - desc 09 ca sysid=0x1817 pid=6417
    - desc 09 ca sysid=0x1818 pid=6427
    - desc 09 ca sysid=0x1819 pid=6437
    - desc 09 ca sysid=0x648 pid=7967
    - desc 09 ca sysid=0xd95 pid=7987
    - desc 09 ca sysid=0x624 pid=6212
    - desc 09 ca sysid=0x500 pid=7035
    - desc 09 ca sysid=0xd98 pid=6505
    - desc 09 ca sysid=0x650 pid=6525
    - desc 09 ca sysid=0x500 pid=7135
    - desc 52 stream_identifier component_tag=1
  * ES pid=3062 streamtype=0x04 streamtype_txt="13818-3 audio (MPEG-2)"
    - desc 09 ca sysid=0x500 pid=8106
    - desc 09 ca sysid=0xb00 pid=1990
    - desc 09 ca sysid=0xd96 pid=6202
    - desc 09 ca sysid=0x100 pid=6126
    - desc 09 ca sysid=0x1810 pid=6122
    - desc 09 ca sysid=0x1817 pid=6417
    - desc 09 ca sysid=0x1818 pid=6427
    - desc 09 ca sysid=0x1819 pid=6437
    - desc 09 ca sysid=0x648 pid=7967
    - desc 09 ca sysid=0xd95 pid=7987
    - desc 09 ca sysid=0x624 pid=6212
    - desc 09 ca sysid=0x500 pid=7035
    - desc 09 ca sysid=0xd98 pid=6505
    - desc 09 ca sysid=0x650 pid=6525
    - desc 09 ca sysid=0x500 pid=7135
    - desc 52 stream_identifier component_tag=2
  * ES pid=301 streamtype=0xc0 streamtype_txt="Unknown"
    - desc c2 unknown length=80 value=4353455f4d5344324353455f50494c314353455f4348414e4353455f455047314353455f455047324353455f465554314353455f415544494353455f465554324353455f4d5344314353455f50494c32
    - desc c6 unknown length=5 value=01000506ff
  * ES pid=222 streamtype=0xc0 streamtype_txt="Unknown"
    - desc c2 unknown length=8 value=434841494e450000
  * ES pid=300 streamtype=0xc1 streamtype_txt="Unknown"
    - desc c2 unknown length=8 value=50494c4f54450000
  * ES pid=253 streamtype=0xc1 streamtype_txt="Unknown"
    - desc c2 unknown length=8 value=44434f4d554e0000
  * ES pid=307 streamtype=0xc1 streamtype_txt="Unknown"
    - desc c2 unknown length=8 value=4c414e5a00000000
  * ES pid=309 streamtype=0xc0 streamtype_txt="Unknown"
    - desc c2 unknown length=8 value=47554941504c5553
  * ES pid=3095 streamtype=0xc1 streamtype_txt="Unknown"
    - desc c2 unknown length=8 value=4c4f524400000000
  * ES pid=3096 streamtype=0xc1 streamtype_txt="Unknown"
    - desc c2 unknown length=8 value=4153545241000000
end PMT
```
A patch is needed inside autoconf_get_pmt_pids() but my understanding of your code is not enough to do this myself. Can you check?

**Comment by malakudi** [comment]
Attaching pmt as decoded by dvbsnoop as well
```
dvbsnoop -adapter 9 316
dvbsnoop V1.4.50 -- http://dvbsnoop.sourceforge.net/ 

------------------------------------------------------------
SECT-Packet: 00000001   PID: 316 (0x013c), Length: 611 (0x0263)
Time received: Sun 2018-11-04  13:52:38.210
------------------------------------------------------------
  0000:  02 b2 60 6f f0 eb 00 00  ff dc f0 00 02 eb f5 f0   ..`o............
  0010:  c1 09 0f 05 00 ff aa 10  01 00 13 01 20 14 03 05   ............ ...
  0020:  06 00 09 04 0b 00 e7 c6  09 04 0d 96 f8 3a 09 3e   .............:.>
  0030:  01 00 f7 ee 41 06 ff ff  ff ff ff ff ff ff ff 39   ....A..........9
  0040:  64 f9 11 00 6a ff ff e0  00 00 00 00 00 00 39 64   d...j.........9d
  0050:  f9 1b 00 6c ff ff e0 00  00 00 00 00 00 39 64 f9   ...l.........9d.
  0060:  25 00 6d ff ff e0 00 00  00 00 00 00 39 64 09 04   %.m.........9d..
  0070:  18 10 f7 ea 09 07 18 17  f9 11 02 00 6a 09 07 18   ............j...
  0080:  18 f9 1b 02 00 6c 09 07  18 19 f9 25 02 00 6d 09   .....l.....%..m.
  0090:  04 06 48 ff 1f 09 04 0d  95 ff 33 09 04 06 24 f8   ..H.......3...$.
  00a0:  44 09 0f 05 00 fb 7b 10  01 00 13 01 20 14 03 05   D.....{..... ...
  00b0:  19 00 09 04 0d 98 f9 69  09 04 06 50 f9 7d 09 0f   .......i...P.}..
  00c0:  05 00 fb df 10 01 00 13  01 20 14 03 05 19 10 52   ......... .....R
  00d0:  01 01 04 eb f6 f0 c1 09  0f 05 00 ff aa 10 01 00   ................
  00e0:  13 01 20 14 03 05 06 00  09 04 0b 00 e7 c6 09 04   .. .............
  00f0:  0d 96 f8 3a 09 3e 01 00  f7 ee 41 06 ff ff ff ff   ...:.>....A.....
  0100:  ff ff ff ff ff 39 64 f9  11 00 6a ff ff e0 00 00   .....9d...j.....
  0110:  00 00 00 00 39 64 f9 1b  00 6c ff ff e0 00 00 00   ....9d...l......
  0120:  00 00 00 39 64 f9 25 00  6d ff ff e0 00 00 00 00   ...9d.%.m.......
  0130:  00 00 39 64 09 04 18 10  f7 ea 09 07 18 17 f9 11   ..9d............
  0140:  02 00 6a 09 07 18 18 f9  1b 02 00 6c 09 07 18 19   ..j........l....
  0150:  f9 25 02 00 6d 09 04 06  48 ff 1f 09 04 0d 95 ff   .%..m...H.......
  0160:  33 09 04 06 24 f8 44 09  0f 05 00 fb 7b 10 01 00   3...$.D.....{...
  0170:  13 01 20 14 03 05 19 00  09 04 0d 98 f9 69 09 04   .. ..........i..
  0180:  06 50 f9 7d 09 0f 05 00  fb df 10 01 00 13 01 20   .P.}........... 
  0190:  14 03 05 19 10 52 01 02  c0 e1 2d f0 59 c2 50 43   .....R....-.Y.PC
  01a0:  53 45 5f 4d 53 44 32 43  53 45 5f 50 49 4c 31 43   SE_MSD2CSE_PIL1C
  01b0:  53 45 5f 43 48 41 4e 43  53 45 5f 45 50 47 31 43   SE_CHANCSE_EPG1C
  01c0:  53 45 5f 45 50 47 32 43  53 45 5f 46 55 54 31 43   SE_EPG2CSE_FUT1C
  01d0:  53 45 5f 41 55 44 49 43  53 45 5f 46 55 54 32 43   SE_AUDICSE_FUT2C
  01e0:  53 45 5f 4d 53 44 31 43  53 45 5f 50 49 4c 32 c6   SE_MSD1CSE_PIL2.
  01f0:  05 01 00 05 06 ff c0 e0  de f0 0a c2 08 43 48 41   .............CHA
  0200:  49 4e 45 00 00 c1 e1 2c  f0 0a c2 08 50 49 4c 4f   INE....,....PILO
  0210:  54 45 00 00 c1 e0 fd f0  0a c2 08 44 43 4f 4d 55   TE.........DCOMU
  0220:  4e 00 00 c1 e1 33 f0 0a  c2 08 4c 41 4e 5a 00 00   N....3....LANZ..
  0230:  00 00 c0 e1 35 f0 0a c2  08 47 55 49 41 50 4c 55   ....5....GUIAPLU
  0240:  53 c1 ec 17 f0 0a c2 08  4c 4f 52 44 00 00 00 00   S.......LORD....
  0250:  c1 ec 18 f0 0a c2 08 41  53 54 52 41 00 00 00 c7   .......ASTRA....
  0260:  de 37 66                                           .7f

PID:  316 (0x013c)

Guess table from table id...
PMT-decoding....
Table_ID: 2 (0x02)  [= Program Map Table (PMT)]
section_syntax_indicator: 1 (0x01)
(fixed '0'): 0 (0x00)
reserved_1: 3 (0x03)
Section_length: 608 (0x0260)
Program_number: 28656 (0x6ff0)
reserved_2: 3 (0x03)
Version_number: 21 (0x15)
current_next_indicator: 1 (0x01)  [= valid now]
Section_number: 0 (0x00)
Last_Section_number: 0 (0x00)
reserved_3: 7 (0x07)
PCR PID: 8156 (0x1fdc)
reserved_4: 15 (0x0f)
Program_info_length: 0 (0x0000)

Stream_type loop: 

    Stream_type: 2 (0x02)  [= ITU-T Rec. H.262 | ISO/IEC 13818-2 Video | ISO/IEC 11172-2 constr. parameter video stream]
    reserved_1: 7 (0x07)
    Elementary_PID: 3061 (0x0bf5)
    reserved_2: 15 (0x0f)
    ES_info_length: 193 (0x00c1)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 15 (0x0f)
            CA_system_ID: 1280 (0x0500)  [= France Telecom (Viaccess)]
            reserved: 7 (0x07)
            CA_PID: 8106 (0x1faa)
            Private Data:
                 0000:  10 01 00 13 01 20 14 03  05 06 00                  ..... .....

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 2816 (0x0b00)  [= Norwegian Telekom (Conax)]
            reserved: 7 (0x07)
            CA_PID: 1990 (0x07c6)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 3478 (0x0d96)  [= Philips (Cryptoworks)]
            reserved: 7 (0x07)
            CA_PID: 6202 (0x183a)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 62 (0x3e)
            CA_system_ID: 256 (0x0100)  [= Canal Plus (Seca/MediaGuard)]
            reserved: 7 (0x07)
            CA_PID: 6126 (0x17ee)
            Private Data:
                 0000:  41 06 ff ff ff ff ff ff  ff ff ff 39 64 f9 11 00   A..........9d...
                 0010:  6a ff ff e0 00 00 00 00  00 00 39 64 f9 1b 00 6c   j.........9d...l
                 0020:  ff ff e0 00 00 00 00 00  00 39 64 f9 25 00 6d ff   .........9d.%.m.
                 0030:  ff e0 00 00 00 00 00 00  39 64                     ........9d

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 6160 (0x1810)  [= Kudelski SA]
            reserved: 7 (0x07)
            CA_PID: 6122 (0x17ea)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 7 (0x07)
            CA_system_ID: 6167 (0x1817)  [= Kudelski SA]
            reserved: 7 (0x07)
            CA_PID: 6417 (0x1911)
            Private Data:
                 0000:  02 00 6a                                           ..j

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 7 (0x07)
            CA_system_ID: 6168 (0x1818)  [= Kudelski SA]
            reserved: 7 (0x07)
            CA_PID: 6427 (0x191b)
            Private Data:
                 0000:  02 00 6c                                           ..l

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 7 (0x07)
            CA_system_ID: 6169 (0x1819)  [= Kudelski SA]
            reserved: 7 (0x07)
            CA_PID: 6437 (0x1925)
            Private Data:
                 0000:  02 00 6d                                           ..m

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 1608 (0x0648)  [= Irdeto]
            reserved: 7 (0x07)
            CA_PID: 7967 (0x1f1f)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 3477 (0x0d95)  [= Philips (Cryptoworks)]
            reserved: 7 (0x07)
            CA_PID: 7987 (0x1f33)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 1572 (0x0624)  [= Irdeto]
            reserved: 7 (0x07)
            CA_PID: 6212 (0x1844)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 15 (0x0f)
            CA_system_ID: 1280 (0x0500)  [= France Telecom (Viaccess)]
            reserved: 7 (0x07)
            CA_PID: 7035 (0x1b7b)
            Private Data:
                 0000:  10 01 00 13 01 20 14 03  05 19 00                  ..... .....

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 3480 (0x0d98)  [= Philips (Cryptoworks)]
            reserved: 7 (0x07)
            CA_PID: 6505 (0x1969)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 1616 (0x0650)  [= Irdeto]
            reserved: 7 (0x07)
            CA_PID: 6525 (0x197d)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 15 (0x0f)
            CA_system_ID: 1280 (0x0500)  [= France Telecom (Viaccess)]
            reserved: 7 (0x07)
            CA_PID: 7135 (0x1bdf)
            Private Data:
                 0000:  10 01 00 13 01 20 14 03  05 19 10                  ..... .....

            DVB-DescriptorTag: 82 (0x52)  [= stream_identifier_descriptor]
            descriptor_length: 1 (0x01)
            component_tag: 1 (0x01)


    Stream_type: 4 (0x04)  [= ISO/IEC 13818-3 Audio]
    reserved_1: 7 (0x07)
    Elementary_PID: 3062 (0x0bf6)
    reserved_2: 15 (0x0f)
    ES_info_length: 193 (0x00c1)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 15 (0x0f)
            CA_system_ID: 1280 (0x0500)  [= France Telecom (Viaccess)]
            reserved: 7 (0x07)
            CA_PID: 8106 (0x1faa)
            Private Data:
                 0000:  10 01 00 13 01 20 14 03  05 06 00                  ..... .....

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 2816 (0x0b00)  [= Norwegian Telekom (Conax)]
            reserved: 7 (0x07)
            CA_PID: 1990 (0x07c6)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 3478 (0x0d96)  [= Philips (Cryptoworks)]
            reserved: 7 (0x07)
            CA_PID: 6202 (0x183a)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 62 (0x3e)
            CA_system_ID: 256 (0x0100)  [= Canal Plus (Seca/MediaGuard)]
            reserved: 7 (0x07)
            CA_PID: 6126 (0x17ee)
            Private Data:
                 0000:  41 06 ff ff ff ff ff ff  ff ff ff 39 64 f9 11 00   A..........9d...
                 0010:  6a ff ff e0 00 00 00 00  00 00 39 64 f9 1b 00 6c   j.........9d...l
                 0020:  ff ff e0 00 00 00 00 00  00 39 64 f9 25 00 6d ff   .........9d.%.m.
                 0030:  ff e0 00 00 00 00 00 00  39 64                     ........9d

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 6160 (0x1810)  [= Kudelski SA]
            reserved: 7 (0x07)
            CA_PID: 6122 (0x17ea)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 7 (0x07)
            CA_system_ID: 6167 (0x1817)  [= Kudelski SA]
            reserved: 7 (0x07)
            CA_PID: 6417 (0x1911)
            Private Data:
                 0000:  02 00 6a                                           ..j

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 7 (0x07)
            CA_system_ID: 6168 (0x1818)  [= Kudelski SA]
            reserved: 7 (0x07)
            CA_PID: 6427 (0x191b)
            Private Data:
                 0000:  02 00 6c                                           ..l

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 7 (0x07)
            CA_system_ID: 6169 (0x1819)  [= Kudelski SA]
            reserved: 7 (0x07)
            CA_PID: 6437 (0x1925)
            Private Data:
                 0000:  02 00 6d                                           ..m

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 1608 (0x0648)  [= Irdeto]
            reserved: 7 (0x07)
            CA_PID: 7967 (0x1f1f)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 3477 (0x0d95)  [= Philips (Cryptoworks)]
            reserved: 7 (0x07)
            CA_PID: 7987 (0x1f33)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 1572 (0x0624)  [= Irdeto]
            reserved: 7 (0x07)
            CA_PID: 6212 (0x1844)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 15 (0x0f)
            CA_system_ID: 1280 (0x0500)  [= France Telecom (Viaccess)]
            reserved: 7 (0x07)
            CA_PID: 7035 (0x1b7b)
            Private Data:
                 0000:  10 01 00 13 01 20 14 03  05 19 00                  ..... .....

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 3480 (0x0d98)  [= Philips (Cryptoworks)]
            reserved: 7 (0x07)
            CA_PID: 6505 (0x1969)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 4 (0x04)
            CA_system_ID: 1616 (0x0650)  [= Irdeto]
            reserved: 7 (0x07)
            CA_PID: 6525 (0x197d)

            MPEG-DescriptorTag: 9 (0x09)  [= CA_descriptor]
            descriptor_length: 15 (0x0f)
            CA_system_ID: 1280 (0x0500)  [= France Telecom (Viaccess)]
            reserved: 7 (0x07)
            CA_PID: 7135 (0x1bdf)
            Private Data:
                 0000:  10 01 00 13 01 20 14 03  05 19 10                  ..... .....

            DVB-DescriptorTag: 82 (0x52)  [= stream_identifier_descriptor]
            descriptor_length: 1 (0x01)
            component_tag: 2 (0x02)


    Stream_type: 192 (0xc0)  [= User private]
    reserved_1: 7 (0x07)
    Elementary_PID: 301 (0x012d)
    reserved_2: 15 (0x0f)
    ES_info_length: 89 (0x0059)

            DVB-DescriptorTag: 194 (0xc2)  [= User defined]
            descriptor_length: 80 (0x50)
            Descriptor-data:
                 0000:  43 53 45 5f 4d 53 44 32  43 53 45 5f 50 49 4c 31   CSE_MSD2CSE_PIL1
                 0010:  43 53 45 5f 43 48 41 4e  43 53 45 5f 45 50 47 31   CSE_CHANCSE_EPG1
                 0020:  43 53 45 5f 45 50 47 32  43 53 45 5f 46 55 54 31   CSE_EPG2CSE_FUT1
                 0030:  43 53 45 5f 41 55 44 49  43 53 45 5f 46 55 54 32   CSE_AUDICSE_FUT2
                 0040:  43 53 45 5f 4d 53 44 31  43 53 45 5f 50 49 4c 32   CSE_MSD1CSE_PIL2

            DVB-DescriptorTag: 198 (0xc6)  [= User defined]
            descriptor_length: 5 (0x05)
            Descriptor-data:
                 0000:  01 00 05 06 ff                                     .....


    Stream_type: 192 (0xc0)  [= User private]
    reserved_1: 7 (0x07)
    Elementary_PID: 222 (0x00de)
    reserved_2: 15 (0x0f)
    ES_info_length: 10 (0x000a)

            DVB-DescriptorTag: 194 (0xc2)  [= User defined]
            descriptor_length: 8 (0x08)
            Descriptor-data:
                 0000:  43 48 41 49 4e 45 00 00                            CHAINE..


    Stream_type: 193 (0xc1)  [= User private]
    reserved_1: 7 (0x07)
    Elementary_PID: 300 (0x012c)
    reserved_2: 15 (0x0f)
    ES_info_length: 10 (0x000a)

            DVB-DescriptorTag: 194 (0xc2)  [= User defined]
            descriptor_length: 8 (0x08)
            Descriptor-data:
                 0000:  50 49 4c 4f 54 45 00 00                            PILOTE..


    Stream_type: 193 (0xc1)  [= User private]
    reserved_1: 7 (0x07)
    Elementary_PID: 253 (0x00fd)
    reserved_2: 15 (0x0f)
    ES_info_length: 10 (0x000a)

            DVB-DescriptorTag: 194 (0xc2)  [= User defined]
            descriptor_length: 8 (0x08)
            Descriptor-data:
                 0000:  44 43 4f 4d 55 4e 00 00                            DCOMUN..


    Stream_type: 193 (0xc1)  [= User private]
    reserved_1: 7 (0x07)
    Elementary_PID: 307 (0x0133)
    reserved_2: 15 (0x0f)
    ES_info_length: 10 (0x000a)

            DVB-DescriptorTag: 194 (0xc2)  [= User defined]
            descriptor_length: 8 (0x08)
            Descriptor-data:
                 0000:  4c 41 4e 5a 00 00 00 00                            LANZ....


    Stream_type: 192 (0xc0)  [= User private]
    reserved_1: 7 (0x07)
    Elementary_PID: 309 (0x0135)
    reserved_2: 15 (0x0f)
    ES_info_length: 10 (0x000a)

            DVB-DescriptorTag: 194 (0xc2)  [= User defined]
            descriptor_length: 8 (0x08)
            Descriptor-data:
                 0000:  47 55 49 41 50 4c 55 53                            GUIAPLUS


    Stream_type: 193 (0xc1)  [= User private]
    reserved_1: 7 (0x07)
    Elementary_PID: 3095 (0x0c17)
    reserved_2: 15 (0x0f)
    ES_info_length: 10 (0x000a)

            DVB-DescriptorTag: 194 (0xc2)  [= User defined]
            descriptor_length: 8 (0x08)
            Descriptor-data:
                 0000:  4c 4f 52 44 00 00 00 00                            LORD....


    Stream_type: 193 (0xc1)  [= User private]
    reserved_1: 7 (0x07)
    Elementary_PID: 3096 (0x0c18)
    reserved_2: 15 (0x0f)
    ES_info_length: 10 (0x000a)

            DVB-DescriptorTag: 194 (0xc2)  [= User defined]
            descriptor_length: 8 (0x08)
            Descriptor-data:
                 0000:  41 53 54 52 41 00 00 00                            ASTRA...

CRC: 3353229158 (0xc7de3766)
==========================================================
```
